
//Worksheet 1 tema 4
//Ejercicio 1

/*Pegar en html

<element click="myScript"></element>
        <p id="XD">AAAAAAAAAAAAAAAAAA></p>





XD
*/


document.getElementById("XD").onclick = function() {myFunction()};

function myFunction() {
  alert("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
}

